[package]
name = "ecs160_hw1-rust"
version = "0.1.0"
edition = "2024"

[dependencies]
serde_json = "1.0"
reqwest = { version = "0.12", features = ["json"] }
tokio = { version = "1", features = ["full"] }
serde = { version = "1.0", features = ["derive"] }
redis = "0.25"
dotenv = "0.15"